name:                samuelschlesinger-info
version:             0.1.0.0
github:              "githubuser/samuelschlesinger-info"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/samuelschlesinger-info#readme>

dependencies:
- pretty-simple
- aeson
- base
- bcrypt
- blaze-html
- bytestring
- cookie
- data-default-class
- directory
- exceptions
- mtl
- http-api-data
- optparse-applicative
- random
- servant-server
- servant-blaze
- stm
- text
- time
- transformers
- unix
- unordered-containers
- uuid
- wai
- wai-extra
- warp
- warp-tls


library:
  source-dirs: src

executables:
  samuelschlesinger-info:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - samuelschlesinger-info

tests:
  samuelschlesinger-info-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - samuelschlesinger-info
